version: "3.1"

services:
  drupalApp:
    image: drupal
    ports: 
        - 8080:80
    volumes:
      - /var/www/html/modules
      - /var/www/html/profiles
      - /var/www/html/themes
      - /var/www/html/sites
    restart: always

  postgresDb:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    restart: always
