version: "3.1"

services:
  drupalApp:
    build:
      context: .
      dockerfile: Dockerfile
    image: custom-drupal
    ports:
      - 8080:80
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-themes:/var/www/html/themes
      - drupal-sites:/var/www/html/sites
    restart: always

  postgresDb:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - /drupal-data:/var/lib/postgresql/data
    restart: always

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-themes:
  drupal-sites:
  drupal-data:
